apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: open-flights-db
spec:
  serviceName: open-flights-db
  replicas: 1
  selector:
    matchLabels:
      app: open-flights-db
  template:
    metadata:
      labels:
        app: open-flights-db
    spec:
      containers:
      - name: db
        image: postgres:12
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: open_flights_development
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard  # Use appropriate storage class
      resources:
        requests:
          storage: 1Gi  # Adjust size as needed
