version: '3.8'

services:
  web:
    image: birbalsarva/open-flights_web:latest  # Specify your custom image here
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgresql://postgres:password@db:5432/open_flights_development"
    
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: open_flights_development
