apiVersion: v1
kind: Service
metadata:
  name: open-flights-web
spec:
  selector:
    app: open-flights-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort  # Use NodePort for simplicity
