apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-flights-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-flights-web
  template:
    metadata:
      labels:
        app: open-flights-web
    spec:
      containers:
        - name: web
          image: birbalsarva/open-flights_web:latest
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_ENV
              value: "development"
            - name: DATABASE_URL
              value: "postgresql://postgres:password@db:5432/open_flights_development"
          volumeMounts:
            - name: app-volume
              mountPath: /app
      volumes:
        - name: app-volume
          emptyDir: {}

