apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: birbalsarva/open-flights_web:latest  # Updated image name
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_ENV
              value: development
            - name: DATABASE_URL
              value: "postgresql://postgres:password@postgresql:5432/open_flights_development"
